server:
  port: 8086

spring:
  redis:
    port: 6377
    host: 49.50.167.74
    password: dlcjf
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/electric_data?serverTimezone=UTC\&characterEncoding=UTF-8
    username: root
    


    