server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/electric_data?serverTimezone=UTC\&characterEncoding=UTF-8
    username: root
    
---
spring:
  redis:
    port: 6379
    host: 127.0.0.1
        
---
spring:
  cache:
    redis:
      time-to-live:
        3000
    